spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: admin
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
kafka:
  topic: example